### PR TITLE
Link api to postgreSQL DB

### PR DESCRIPTION
**Pull request by Alexandria**
**### Overview:**
Setup my express api 
Added necessary packages to create my express api
Linked the api to the postgres database

**### Screenshots:**

Postgres Database
Postgres Database

View from browser
View from browser

**### Review Checklist:**
- [ ] Merge destination is correct
- [ ] Tests cases have been added where appropriate (Jest, Loki, Cypress)
- [ ] Code is correct as understood and conforms to quality standards

### CODE REVIEW

**Review by kileybublitz — COMMENTED** [review]
One thing to keep in mind, might want to add the `.env` to the gitignore so that your database info isn't available on github 😄

**Comment by kileybublitz** [comment]
I _think_ the build directory should also be in the gitignore... please correct me if I'm wrong @ckhicks @blaketarter

**Review by ckhicks — DISMISSED** [review]

**Review by kileybublitz — CHANGES_REQUESTED** [review]
Looks great! Just make those couple of updates with the gitignore and you'll be good to go!

**Comment by ckhicks** [comment]
Woops, yep, need the `.env` ignore, my bad.

@KileyAdams92 Unless we're building on the server the build dir would need to be included in the repo. I defer to @blaketarter on that one if we're handling it as part of the deployment pipeline.

**Review by blaketarter — CHANGES_REQUESTED** [review]
Yeah we should make sure to not include `.env` for security reasons and `build` in the git repo as the server will build that as a part of its deploy process.

**Review by kileybublitz — CHANGES_REQUESTED** [review]
Good job, just need to add the build directory into the .gitignore too 👍

**Review by blaketarter — CHANGES_REQUESTED** [review]
Don't forget to also remove the `.env` file and `build` folder from the git repo. Since they were already tracked when you added them to the `.gitignore` they still show up in the PR.

**Review by blaketarter — APPROVED** [review]
👍 Good work!

**Review by ckhicks — APPROVED** [review]

**Review by kileybublitz — APPROVED** [review]

**Pull request merged**
